### ISSUE TITLE
Regression introduced by PR 118 - topic_queue_consumer.py ModuleNotFoundError: No module named 'swagger_server

### ISSUE THREAD

**Issue by italovalcy** [atlanticwave-sdx/sdx-lc#119]
Hi,

It looks like the PR #118  introduced a regression on SDX-LC:

```
[0;m[0KUsing docker image sha256:e59530f59b123fc7b18f518748650ca75a9d4d77542c94da6bda0061745d7bdb for awsdx/sdx-lc:latest with digest awsdx/sdx-lc@sha256:76e0c9eb24416b7da4e6dcf1b5445d7424acd7b3114f6707c446c9f5cec8d711 ...
...
2024-05-18T02:29:42.059977752Z Connection to RabbitMQ established successfully
2024-05-18T02:29:42.113822937Z + python3 -m sdx_lc
2024-05-18T02:29:45.367401144Z Traceback (most recent call last):
2024-05-18T02:29:45.367450146Z   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2024-05-18T02:29:45.367456260Z     return _run_code(code, main_globals, None,
2024-05-18T02:29:45.367460758Z   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
2024-05-18T02:29:45.367465271Z     exec(code, run_globals)
2024-05-18T02:29:45.367469367Z   File "/usr/src/app/sdx_lc/__main__.py", line 14, in <module>
2024-05-18T02:29:45.367473941Z     from sdx_lc.messaging.topic_queue_consumer import *
2024-05-18T02:29:45.367478491Z   File "/usr/src/app/sdx_lc/messaging/topic_queue_consumer.py", line 10, in <module>
2024-05-18T02:29:45.367482768Z     from swagger_server.utils.db_utils import DbUtils
2024-05-18T02:29:45.367486735Z ModuleNotFoundError: No module named 'swagger_server'

```

I believe it would be a good idea to run a few basic tests before approving/merging a PR to avoid this type of situation.

Ccing @YufengXin and @sajith to provide any help on this.

**Comment by YufengXin** [comment]
Thanks for reporting this. 

@congwang09 could you make the change (in MQ piece?), replacing the name from swagger-server to sdx-lc?

I've been making the series of updates across the 4 repos to address the user port/user vlan request.

And I used the opportunity to make a few changes we wanted before, mainly a few naming conventions.

Now the changes on the datamodel, pce, and sdx-lc have been complete. we'll run more system tests in sdx-controller, and do the final tagging.
